### ISSUE TITLE
502 bad gateway on raspberry pi 3

### ISSUE THREAD

**Issue by narduin** [YunoHost-Apps/cryptpad_ynh#23] opened 2018-03-28 08:35 UTC
Hello !
I tried to install cryptpad on my RPI3. Everythink looked fine during the install but I can't access the app…
The content of /var/log/cryptpad/cryptpad.log isn't much help (for me anyway) :
```
loading task scheduler

[2018-03-28T08:22:13.584Z] server available http://[::]:3000
Cryptpad is customizable, see customize.dist/readme.md for details
```                                                                                                                                                                                   
Thanks for the help !

**Comment by frju365** [comment] 2018-03-28 09:01
Yes, pretty strange. Can you share me the result of  : `service cryptpad status` ?

**Comment by patatus** [comment] 2018-03-28 09:28
I completely forgot to check that…
Here it is :
```
cryptpad.service - CryptPad is an encrypted PAD Creator
   Loaded: loaded (/etc/systemd/system/cryptpad.service; enabled)                                                                                                                                                                                    
   Active: failed (Result: start-limit) since Wed 2018-03-28 08:22:13 UTC; 1h 4min ago
  Process: 31067 ExecStart=/bin/bash -c exec /usr/local/n/versions/node/8/bin/node  server.js  | tee /var/log/cryptpad/cryptpad.log (code=exited, status=0/SUCCESS)                                                                                  
  Process: 31046 ExecStartPre=/opt/node_n/bin/n -q 8 (code=exited, status=0/SUCCESS)                                                                                                                                                                 
 Main PID: 31067 (code=exited, status=0/SUCCESS)   
```

**Comment by klorydryk** [comment] 2018-04-23 14:15
I confirm the same problem on my own. :(

**Comment by ericgaspar** [comment] 2021-02-05 22:58
closing

**Closed by ericgaspar** 2021-02-05 22:58 UTC
Labels: bug

**Comment by klorydryk** [comment] 2021-02-06 19:49
Closing because ? Is it solved?

**Comment by ericgaspar** [comment] 2021-02-06 21:28
Closing because the problem is almost 3 years old and the package has changed a lot since then. If the problem persists, please reopen a new one.
